export const landingText = {
  es: {
    buyNow: 'Comprar Ahora',
    shopNow: 'Comprar Ahora',
    addToCart: 'Agregar al Carrito',
    whyChoose: '¿Por qué elegir este producto?',
    gallery: 'Galería del Producto',
    socialProofSub: 'Miles de clientes satisfechos en toda América Latina',
    specialOffer: 'Precio Especial',
    save: 'Ahorras',
    faq: 'Preguntas Frecuentes',
    readyToBuy: '¿Listo para hacer tu compra?',
    ctaSubtitle: 'Compra segura con garantía de satisfacción. Recibe tu producto en 48-72 horas.',
    shipping: '✓ Envío rápido y seguro',
    guarantee: '✓ Garantía de satisfacción',
    support: '✓ Soporte al cliente 24/7',
    trustedBy: 'Trusted by thousands',
    investment: 'Precio',
    whyLoveIt: '¿Por qué te encantará?',
    qualityLabel: 'Mejor Calidad',
    qualityDesc: 'Producto verificado y de alta calidad',
    shippingLabel: 'Envío Rápido',
    shippingDesc: 'Entregado en 2-3 días hábiles',
    warrantyLabel: 'Garantía',
    warrantyDesc: 'Devolución sin preguntas en 30 días',
    navBuy: 'Comprar',
    limitedStock: 'Inventario limitado',
    footerTagline: 'Landings inteligentes para tu negocio',
    inStock: 'En venta',
    poweredBy: 'Plataforma:',
    allRights: 'Todos los derechos reservados.',
    showcase: 'Galería',
    productLabel: 'Producto',
    statusLabel: 'Estado',
    heroSubtitle: 'Descubre la combinación perfecta de calidad, estilo y precio. ¡Únete a miles de clientes satisfechos hoy!',
    benefitsSubtitle: 'Calidad premium a un precio inigualable',
    footerTagline2: 'Productos premium a los mejores precios',
    premiumBadge: 'Producto Premium',
    heroCraft: 'Fabricado con precisión y cuidado para el consumidor moderno.',
  },
  en: {
    buyNow: 'Buy Now',
    shopNow: 'Shop Now',
    addToCart: 'Add to Cart',
    whyChoose: 'Why Choose This Product?',
    gallery: 'Product Gallery',
    socialProofSub: 'Trusted by thousands of happy customers worldwide',
    specialOffer: 'Special Price',
    save: 'You Save',
    faq: 'Frequently Asked Questions',
    readyToBuy: 'Ready to Buy?',
    ctaSubtitle: 'Secure checkout with satisfaction guarantee. Receive your product in 2-3 business days.',
    shipping: '✓ Fast & secure shipping',
    guarantee: '✓ Satisfaction guarantee',
    support: '✓ 24/7 customer support',
    trustedBy: 'Trusted by thousands',
    investment: 'Price',
    whyLoveIt: "Why You'll Love It",
    qualityLabel: 'Best Quality',
    qualityDesc: 'Verified high-quality product',
    shippingLabel: 'Fast Shipping',
    shippingDesc: 'Delivered in 2-3 business days',
    warrantyLabel: 'Warranty',
    warrantyDesc: '30-day no-questions return policy',
    navBuy: 'Buy',
    limitedStock: 'Limited inventory',
    footerTagline: 'Smart landing pages for your business',
    inStock: 'Available',
    poweredBy: 'Platform:',
    allRights: 'All rights reserved.',
    showcase: 'Showcase',
    productLabel: 'Product',
    statusLabel: 'Status',
    heroSubtitle: 'Discover the perfect blend of quality, style, and affordability. Join thousands of happy customers today!',
    benefitsSubtitle: 'Premium quality at an unbeatable price',
    footerTagline2: 'Premium products at great prices',
    premiumBadge: 'Premium Product',
    heroCraft: 'Crafted with precision and care for the modern consumer.',
  },
}
